// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy_common_definitions.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_policy_5fcommon_5fdefinitions_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_policy_5fcommon_5fdefinitions_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_policy_5fcommon_5fdefinitions_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_policy_5fcommon_5fdefinitions_2eproto {
  static const uint32_t offsets[];
};
namespace enterprise_management {
class BooleanPolicyProto;
struct BooleanPolicyProtoDefaultTypeInternal;
extern BooleanPolicyProtoDefaultTypeInternal _BooleanPolicyProto_default_instance_;
class IntegerPolicyProto;
struct IntegerPolicyProtoDefaultTypeInternal;
extern IntegerPolicyProtoDefaultTypeInternal _IntegerPolicyProto_default_instance_;
class PolicyOptions;
struct PolicyOptionsDefaultTypeInternal;
extern PolicyOptionsDefaultTypeInternal _PolicyOptions_default_instance_;
class StringList;
struct StringListDefaultTypeInternal;
extern StringListDefaultTypeInternal _StringList_default_instance_;
class StringListPolicyProto;
struct StringListPolicyProtoDefaultTypeInternal;
extern StringListPolicyProtoDefaultTypeInternal _StringListPolicyProto_default_instance_;
class StringPolicyProto;
struct StringPolicyProtoDefaultTypeInternal;
extern StringPolicyProtoDefaultTypeInternal _StringPolicyProto_default_instance_;
}  // namespace enterprise_management
PROTOBUF_NAMESPACE_OPEN
template<> ::enterprise_management::BooleanPolicyProto* Arena::CreateMaybeMessage<::enterprise_management::BooleanPolicyProto>(Arena*);
template<> ::enterprise_management::IntegerPolicyProto* Arena::CreateMaybeMessage<::enterprise_management::IntegerPolicyProto>(Arena*);
template<> ::enterprise_management::PolicyOptions* Arena::CreateMaybeMessage<::enterprise_management::PolicyOptions>(Arena*);
template<> ::enterprise_management::StringList* Arena::CreateMaybeMessage<::enterprise_management::StringList>(Arena*);
template<> ::enterprise_management::StringListPolicyProto* Arena::CreateMaybeMessage<::enterprise_management::StringListPolicyProto>(Arena*);
template<> ::enterprise_management::StringPolicyProto* Arena::CreateMaybeMessage<::enterprise_management::StringPolicyProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace enterprise_management {

enum PolicyOptions_PolicyMode : int {
  PolicyOptions_PolicyMode_MANDATORY = 0,
  PolicyOptions_PolicyMode_RECOMMENDED = 1,
  PolicyOptions_PolicyMode_UNSET = 2
};
bool PolicyOptions_PolicyMode_IsValid(int value);
constexpr PolicyOptions_PolicyMode PolicyOptions_PolicyMode_PolicyMode_MIN = PolicyOptions_PolicyMode_MANDATORY;
constexpr PolicyOptions_PolicyMode PolicyOptions_PolicyMode_PolicyMode_MAX = PolicyOptions_PolicyMode_UNSET;
constexpr int PolicyOptions_PolicyMode_PolicyMode_ARRAYSIZE = PolicyOptions_PolicyMode_PolicyMode_MAX + 1;

const std::string& PolicyOptions_PolicyMode_Name(PolicyOptions_PolicyMode value);
template<typename T>
inline const std::string& PolicyOptions_PolicyMode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PolicyOptions_PolicyMode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PolicyOptions_PolicyMode_Name.");
  return PolicyOptions_PolicyMode_Name(static_cast<PolicyOptions_PolicyMode>(enum_t_value));
}
bool PolicyOptions_PolicyMode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PolicyOptions_PolicyMode* value);
// ===================================================================

class StringList final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:enterprise_management.StringList) */ {
 public:
  inline StringList() : StringList(nullptr) {}
  ~StringList() override;
  explicit PROTOBUF_CONSTEXPR StringList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StringList(const StringList& from);
  StringList(StringList&& from) noexcept
    : StringList() {
    *this = ::std::move(from);
  }

  inline StringList& operator=(const StringList& from) {
    CopyFrom(from);
    return *this;
  }
  inline StringList& operator=(StringList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const StringList& default_instance() {
    return *internal_default_instance();
  }
  static inline const StringList* internal_default_instance() {
    return reinterpret_cast<const StringList*>(
               &_StringList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(StringList& a, StringList& b) {
    a.Swap(&b);
  }
  inline void Swap(StringList* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StringList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StringList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StringList>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const StringList& from);
  void MergeFrom(const StringList& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(StringList* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "enterprise_management.StringList";
  }
  protected:
  explicit StringList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEntriesFieldNumber = 1,
  };
  // repeated string entries = 1;
  int entries_size() const;
  private:
  int _internal_entries_size() const;
  public:
  void clear_entries();
  const std::string& entries(int index) const;
  std::string* mutable_entries(int index);
  void set_entries(int index, const std::string& value);
  void set_entries(int index, std::string&& value);
  void set_entries(int index, const char* value);
  void set_entries(int index, const char* value, size_t size);
  std::string* add_entries();
  void add_entries(const std::string& value);
  void add_entries(std::string&& value);
  void add_entries(const char* value);
  void add_entries(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& entries() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_entries();
  private:
  const std::string& _internal_entries(int index) const;
  std::string* _internal_add_entries();
  public:

  // @@protoc_insertion_point(class_scope:enterprise_management.StringList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> entries_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_policy_5fcommon_5fdefinitions_2eproto;
};
// -------------------------------------------------------------------

class PolicyOptions final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:enterprise_management.PolicyOptions) */ {
 public:
  inline PolicyOptions() : PolicyOptions(nullptr) {}
  ~PolicyOptions() override;
  explicit PROTOBUF_CONSTEXPR PolicyOptions(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PolicyOptions(const PolicyOptions& from);
  PolicyOptions(PolicyOptions&& from) noexcept
    : PolicyOptions() {
    *this = ::std::move(from);
  }

  inline PolicyOptions& operator=(const PolicyOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline PolicyOptions& operator=(PolicyOptions&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const PolicyOptions& default_instance() {
    return *internal_default_instance();
  }
  static inline const PolicyOptions* internal_default_instance() {
    return reinterpret_cast<const PolicyOptions*>(
               &_PolicyOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PolicyOptions& a, PolicyOptions& b) {
    a.Swap(&b);
  }
  inline void Swap(PolicyOptions* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PolicyOptions* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PolicyOptions* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PolicyOptions>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const PolicyOptions& from);
  void MergeFrom(const PolicyOptions& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PolicyOptions* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "enterprise_management.PolicyOptions";
  }
  protected:
  explicit PolicyOptions(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  typedef PolicyOptions_PolicyMode PolicyMode;
  static constexpr PolicyMode MANDATORY =
    PolicyOptions_PolicyMode_MANDATORY;
  static constexpr PolicyMode RECOMMENDED =
    PolicyOptions_PolicyMode_RECOMMENDED;
  static constexpr PolicyMode UNSET =
    PolicyOptions_PolicyMode_UNSET;
  static inline bool PolicyMode_IsValid(int value) {
    return PolicyOptions_PolicyMode_IsValid(value);
  }
  static constexpr PolicyMode PolicyMode_MIN =
    PolicyOptions_PolicyMode_PolicyMode_MIN;
  static constexpr PolicyMode PolicyMode_MAX =
    PolicyOptions_PolicyMode_PolicyMode_MAX;
  static constexpr int PolicyMode_ARRAYSIZE =
    PolicyOptions_PolicyMode_PolicyMode_ARRAYSIZE;
  template<typename T>
  static inline const std::string& PolicyMode_Name(T enum_t_value) {
    static_assert(::std::is_same<T, PolicyMode>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function PolicyMode_Name.");
    return PolicyOptions_PolicyMode_Name(enum_t_value);
  }
  static inline bool PolicyMode_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      PolicyMode* value) {
    return PolicyOptions_PolicyMode_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kModeFieldNumber = 1,
  };
  // optional .enterprise_management.PolicyOptions.PolicyMode mode = 1 [default = MANDATORY];
  bool has_mode() const;
  private:
  bool _internal_has_mode() const;
  public:
  void clear_mode();
  ::enterprise_management::PolicyOptions_PolicyMode mode() const;
  void set_mode(::enterprise_management::PolicyOptions_PolicyMode value);
  private:
  ::enterprise_management::PolicyOptions_PolicyMode _internal_mode() const;
  void _internal_set_mode(::enterprise_management::PolicyOptions_PolicyMode value);
  public:

  // @@protoc_insertion_point(class_scope:enterprise_management.PolicyOptions)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    int mode_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_policy_5fcommon_5fdefinitions_2eproto;
};
// -------------------------------------------------------------------

class BooleanPolicyProto final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:enterprise_management.BooleanPolicyProto) */ {
 public:
  inline BooleanPolicyProto() : BooleanPolicyProto(nullptr) {}
  ~BooleanPolicyProto() override;
  explicit PROTOBUF_CONSTEXPR BooleanPolicyProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BooleanPolicyProto(const BooleanPolicyProto& from);
  BooleanPolicyProto(BooleanPolicyProto&& from) noexcept
    : BooleanPolicyProto() {
    *this = ::std::move(from);
  }

  inline BooleanPolicyProto& operator=(const BooleanPolicyProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline BooleanPolicyProto& operator=(BooleanPolicyProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const BooleanPolicyProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const BooleanPolicyProto* internal_default_instance() {
    return reinterpret_cast<const BooleanPolicyProto*>(
               &_BooleanPolicyProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(BooleanPolicyProto& a, BooleanPolicyProto& b) {
    a.Swap(&b);
  }
  inline void Swap(BooleanPolicyProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BooleanPolicyProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BooleanPolicyProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BooleanPolicyProto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const BooleanPolicyProto& from);
  void MergeFrom(const BooleanPolicyProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BooleanPolicyProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "enterprise_management.BooleanPolicyProto";
  }
  protected:
  explicit BooleanPolicyProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPolicyOptionsFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // optional .enterprise_management.PolicyOptions policy_options = 1;
  bool has_policy_options() const;
  private:
  bool _internal_has_policy_options() const;
  public:
  void clear_policy_options();
  const ::enterprise_management::PolicyOptions& policy_options() const;
  PROTOBUF_NODISCARD ::enterprise_management::PolicyOptions* release_policy_options();
  ::enterprise_management::PolicyOptions* mutable_policy_options();
  void set_allocated_policy_options(::enterprise_management::PolicyOptions* policy_options);
  private:
  const ::enterprise_management::PolicyOptions& _internal_policy_options() const;
  ::enterprise_management::PolicyOptions* _internal_mutable_policy_options();
  public:
  void unsafe_arena_set_allocated_policy_options(
      ::enterprise_management::PolicyOptions* policy_options);
  ::enterprise_management::PolicyOptions* unsafe_arena_release_policy_options();

  // optional bool value = 2;
  bool has_value() const;
  private:
  bool _internal_has_value() const;
  public:
  void clear_value();
  bool value() const;
  void set_value(bool value);
  private:
  bool _internal_value() const;
  void _internal_set_value(bool value);
  public:

  // @@protoc_insertion_point(class_scope:enterprise_management.BooleanPolicyProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::enterprise_management::PolicyOptions* policy_options_;
    bool value_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_policy_5fcommon_5fdefinitions_2eproto;
};
// -------------------------------------------------------------------

class IntegerPolicyProto final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:enterprise_management.IntegerPolicyProto) */ {
 public:
  inline IntegerPolicyProto() : IntegerPolicyProto(nullptr) {}
  ~IntegerPolicyProto() override;
  explicit PROTOBUF_CONSTEXPR IntegerPolicyProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  IntegerPolicyProto(const IntegerPolicyProto& from);
  IntegerPolicyProto(IntegerPolicyProto&& from) noexcept
    : IntegerPolicyProto() {
    *this = ::std::move(from);
  }

  inline IntegerPolicyProto& operator=(const IntegerPolicyProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline IntegerPolicyProto& operator=(IntegerPolicyProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const IntegerPolicyProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const IntegerPolicyProto* internal_default_instance() {
    return reinterpret_cast<const IntegerPolicyProto*>(
               &_IntegerPolicyProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(IntegerPolicyProto& a, IntegerPolicyProto& b) {
    a.Swap(&b);
  }
  inline void Swap(IntegerPolicyProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IntegerPolicyProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IntegerPolicyProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<IntegerPolicyProto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const IntegerPolicyProto& from);
  void MergeFrom(const IntegerPolicyProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(IntegerPolicyProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "enterprise_management.IntegerPolicyProto";
  }
  protected:
  explicit IntegerPolicyProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPolicyOptionsFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // optional .enterprise_management.PolicyOptions policy_options = 1;
  bool has_policy_options() const;
  private:
  bool _internal_has_policy_options() const;
  public:
  void clear_policy_options();
  const ::enterprise_management::PolicyOptions& policy_options() const;
  PROTOBUF_NODISCARD ::enterprise_management::PolicyOptions* release_policy_options();
  ::enterprise_management::PolicyOptions* mutable_policy_options();
  void set_allocated_policy_options(::enterprise_management::PolicyOptions* policy_options);
  private:
  const ::enterprise_management::PolicyOptions& _internal_policy_options() const;
  ::enterprise_management::PolicyOptions* _internal_mutable_policy_options();
  public:
  void unsafe_arena_set_allocated_policy_options(
      ::enterprise_management::PolicyOptions* policy_options);
  ::enterprise_management::PolicyOptions* unsafe_arena_release_policy_options();

  // optional int64 value = 2;
  bool has_value() const;
  private:
  bool _internal_has_value() const;
  public:
  void clear_value();
  int64_t value() const;
  void set_value(int64_t value);
  private:
  int64_t _internal_value() const;
  void _internal_set_value(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:enterprise_management.IntegerPolicyProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::enterprise_management::PolicyOptions* policy_options_;
    int64_t value_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_policy_5fcommon_5fdefinitions_2eproto;
};
// -------------------------------------------------------------------

class StringPolicyProto final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:enterprise_management.StringPolicyProto) */ {
 public:
  inline StringPolicyProto() : StringPolicyProto(nullptr) {}
  ~StringPolicyProto() override;
  explicit PROTOBUF_CONSTEXPR StringPolicyProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StringPolicyProto(const StringPolicyProto& from);
  StringPolicyProto(StringPolicyProto&& from) noexcept
    : StringPolicyProto() {
    *this = ::std::move(from);
  }

  inline StringPolicyProto& operator=(const StringPolicyProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline StringPolicyProto& operator=(StringPolicyProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const StringPolicyProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const StringPolicyProto* internal_default_instance() {
    return reinterpret_cast<const StringPolicyProto*>(
               &_StringPolicyProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(StringPolicyProto& a, StringPolicyProto& b) {
    a.Swap(&b);
  }
  inline void Swap(StringPolicyProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StringPolicyProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StringPolicyProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StringPolicyProto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const StringPolicyProto& from);
  void MergeFrom(const StringPolicyProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(StringPolicyProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "enterprise_management.StringPolicyProto";
  }
  protected:
  explicit StringPolicyProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 2,
    kPolicyOptionsFieldNumber = 1,
  };
  // optional string value = 2;
  bool has_value() const;
  private:
  bool _internal_has_value() const;
  public:
  void clear_value();
  const std::string& value() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_value(ArgT0&& arg0, ArgT... args);
  std::string* mutable_value();
  PROTOBUF_NODISCARD std::string* release_value();
  void set_allocated_value(std::string* value);
  private:
  const std::string& _internal_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_value(const std::string& value);
  std::string* _internal_mutable_value();
  public:

  // optional .enterprise_management.PolicyOptions policy_options = 1;
  bool has_policy_options() const;
  private:
  bool _internal_has_policy_options() const;
  public:
  void clear_policy_options();
  const ::enterprise_management::PolicyOptions& policy_options() const;
  PROTOBUF_NODISCARD ::enterprise_management::PolicyOptions* release_policy_options();
  ::enterprise_management::PolicyOptions* mutable_policy_options();
  void set_allocated_policy_options(::enterprise_management::PolicyOptions* policy_options);
  private:
  const ::enterprise_management::PolicyOptions& _internal_policy_options() const;
  ::enterprise_management::PolicyOptions* _internal_mutable_policy_options();
  public:
  void unsafe_arena_set_allocated_policy_options(
      ::enterprise_management::PolicyOptions* policy_options);
  ::enterprise_management::PolicyOptions* unsafe_arena_release_policy_options();

  // @@protoc_insertion_point(class_scope:enterprise_management.StringPolicyProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
    ::enterprise_management::PolicyOptions* policy_options_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_policy_5fcommon_5fdefinitions_2eproto;
};
// -------------------------------------------------------------------

class StringListPolicyProto final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:enterprise_management.StringListPolicyProto) */ {
 public:
  inline StringListPolicyProto() : StringListPolicyProto(nullptr) {}
  ~StringListPolicyProto() override;
  explicit PROTOBUF_CONSTEXPR StringListPolicyProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StringListPolicyProto(const StringListPolicyProto& from);
  StringListPolicyProto(StringListPolicyProto&& from) noexcept
    : StringListPolicyProto() {
    *this = ::std::move(from);
  }

  inline StringListPolicyProto& operator=(const StringListPolicyProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline StringListPolicyProto& operator=(StringListPolicyProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const StringListPolicyProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const StringListPolicyProto* internal_default_instance() {
    return reinterpret_cast<const StringListPolicyProto*>(
               &_StringListPolicyProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(StringListPolicyProto& a, StringListPolicyProto& b) {
    a.Swap(&b);
  }
  inline void Swap(StringListPolicyProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StringListPolicyProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StringListPolicyProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StringListPolicyProto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const StringListPolicyProto& from);
  void MergeFrom(const StringListPolicyProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(StringListPolicyProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "enterprise_management.StringListPolicyProto";
  }
  protected:
  explicit StringListPolicyProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPolicyOptionsFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // optional .enterprise_management.PolicyOptions policy_options = 1;
  bool has_policy_options() const;
  private:
  bool _internal_has_policy_options() const;
  public:
  void clear_policy_options();
  const ::enterprise_management::PolicyOptions& policy_options() const;
  PROTOBUF_NODISCARD ::enterprise_management::PolicyOptions* release_policy_options();
  ::enterprise_management::PolicyOptions* mutable_policy_options();
  void set_allocated_policy_options(::enterprise_management::PolicyOptions* policy_options);
  private:
  const ::enterprise_management::PolicyOptions& _internal_policy_options() const;
  ::enterprise_management::PolicyOptions* _internal_mutable_policy_options();
  public:
  void unsafe_arena_set_allocated_policy_options(
      ::enterprise_management::PolicyOptions* policy_options);
  ::enterprise_management::PolicyOptions* unsafe_arena_release_policy_options();

  // optional .enterprise_management.StringList value = 2;
  bool has_value() const;
  private:
  bool _internal_has_value() const;
  public:
  void clear_value();
  const ::enterprise_management::StringList& value() const;
  PROTOBUF_NODISCARD ::enterprise_management::StringList* release_value();
  ::enterprise_management::StringList* mutable_value();
  void set_allocated_value(::enterprise_management::StringList* value);
  private:
  const ::enterprise_management::StringList& _internal_value() const;
  ::enterprise_management::StringList* _internal_mutable_value();
  public:
  void unsafe_arena_set_allocated_value(
      ::enterprise_management::StringList* value);
  ::enterprise_management::StringList* unsafe_arena_release_value();

  // @@protoc_insertion_point(class_scope:enterprise_management.StringListPolicyProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::enterprise_management::PolicyOptions* policy_options_;
    ::enterprise_management::StringList* value_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_policy_5fcommon_5fdefinitions_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StringList

// repeated string entries = 1;
inline int StringList::_internal_entries_size() const {
  return _impl_.entries_.size();
}
inline int StringList::entries_size() const {
  return _internal_entries_size();
}
inline void StringList::clear_entries() {
  _impl_.entries_.Clear();
}
inline std::string* StringList::add_entries() {
  std::string* _s = _internal_add_entries();
  // @@protoc_insertion_point(field_add_mutable:enterprise_management.StringList.entries)
  return _s;
}
inline const std::string& StringList::_internal_entries(int index) const {
  return _impl_.entries_.Get(index);
}
inline const std::string& StringList::entries(int index) const {
  // @@protoc_insertion_point(field_get:enterprise_management.StringList.entries)
  return _internal_entries(index);
}
inline std::string* StringList::mutable_entries(int index) {
  // @@protoc_insertion_point(field_mutable:enterprise_management.StringList.entries)
  return _impl_.entries_.Mutable(index);
}
inline void StringList::set_entries(int index, const std::string& value) {
  _impl_.entries_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:enterprise_management.StringList.entries)
}
inline void StringList::set_entries(int index, std::string&& value) {
  _impl_.entries_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:enterprise_management.StringList.entries)
}
inline void StringList::set_entries(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.entries_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:enterprise_management.StringList.entries)
}
inline void StringList::set_entries(int index, const char* value, size_t size) {
  _impl_.entries_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:enterprise_management.StringList.entries)
}
inline std::string* StringList::_internal_add_entries() {
  return _impl_.entries_.Add();
}
inline void StringList::add_entries(const std::string& value) {
  _impl_.entries_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:enterprise_management.StringList.entries)
}
inline void StringList::add_entries(std::string&& value) {
  _impl_.entries_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:enterprise_management.StringList.entries)
}
inline void StringList::add_entries(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.entries_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:enterprise_management.StringList.entries)
}
inline void StringList::add_entries(const char* value, size_t size) {
  _impl_.entries_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:enterprise_management.StringList.entries)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
StringList::entries() const {
  // @@protoc_insertion_point(field_list:enterprise_management.StringList.entries)
  return _impl_.entries_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
StringList::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:enterprise_management.StringList.entries)
  return &_impl_.entries_;
}

// -------------------------------------------------------------------

// PolicyOptions

// optional .enterprise_management.PolicyOptions.PolicyMode mode = 1 [default = MANDATORY];
inline bool PolicyOptions::_internal_has_mode() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool PolicyOptions::has_mode() const {
  return _internal_has_mode();
}
inline void PolicyOptions::clear_mode() {
  _impl_.mode_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::enterprise_management::PolicyOptions_PolicyMode PolicyOptions::_internal_mode() const {
  return static_cast< ::enterprise_management::PolicyOptions_PolicyMode >(_impl_.mode_);
}
inline ::enterprise_management::PolicyOptions_PolicyMode PolicyOptions::mode() const {
  // @@protoc_insertion_point(field_get:enterprise_management.PolicyOptions.mode)
  return _internal_mode();
}
inline void PolicyOptions::_internal_set_mode(::enterprise_management::PolicyOptions_PolicyMode value) {
  assert(::enterprise_management::PolicyOptions_PolicyMode_IsValid(value));
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.mode_ = value;
}
inline void PolicyOptions::set_mode(::enterprise_management::PolicyOptions_PolicyMode value) {
  _internal_set_mode(value);
  // @@protoc_insertion_point(field_set:enterprise_management.PolicyOptions.mode)
}

// -------------------------------------------------------------------

// BooleanPolicyProto

// optional .enterprise_management.PolicyOptions policy_options = 1;
inline bool BooleanPolicyProto::_internal_has_policy_options() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.policy_options_ != nullptr);
  return value;
}
inline bool BooleanPolicyProto::has_policy_options() const {
  return _internal_has_policy_options();
}
inline void BooleanPolicyProto::clear_policy_options() {
  if (_impl_.policy_options_ != nullptr) _impl_.policy_options_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::enterprise_management::PolicyOptions& BooleanPolicyProto::_internal_policy_options() const {
  const ::enterprise_management::PolicyOptions* p = _impl_.policy_options_;
  return p != nullptr ? *p : reinterpret_cast<const ::enterprise_management::PolicyOptions&>(
      ::enterprise_management::_PolicyOptions_default_instance_);
}
inline const ::enterprise_management::PolicyOptions& BooleanPolicyProto::policy_options() const {
  // @@protoc_insertion_point(field_get:enterprise_management.BooleanPolicyProto.policy_options)
  return _internal_policy_options();
}
inline void BooleanPolicyProto::unsafe_arena_set_allocated_policy_options(
    ::enterprise_management::PolicyOptions* policy_options) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.policy_options_);
  }
  _impl_.policy_options_ = policy_options;
  if (policy_options) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:enterprise_management.BooleanPolicyProto.policy_options)
}
inline ::enterprise_management::PolicyOptions* BooleanPolicyProto::release_policy_options() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::enterprise_management::PolicyOptions* temp = _impl_.policy_options_;
  _impl_.policy_options_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::enterprise_management::PolicyOptions* BooleanPolicyProto::unsafe_arena_release_policy_options() {
  // @@protoc_insertion_point(field_release:enterprise_management.BooleanPolicyProto.policy_options)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::enterprise_management::PolicyOptions* temp = _impl_.policy_options_;
  _impl_.policy_options_ = nullptr;
  return temp;
}
inline ::enterprise_management::PolicyOptions* BooleanPolicyProto::_internal_mutable_policy_options() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.policy_options_ == nullptr) {
    auto* p = CreateMaybeMessage<::enterprise_management::PolicyOptions>(GetArenaForAllocation());
    _impl_.policy_options_ = p;
  }
  return _impl_.policy_options_;
}
inline ::enterprise_management::PolicyOptions* BooleanPolicyProto::mutable_policy_options() {
  ::enterprise_management::PolicyOptions* _msg = _internal_mutable_policy_options();
  // @@protoc_insertion_point(field_mutable:enterprise_management.BooleanPolicyProto.policy_options)
  return _msg;
}
inline void BooleanPolicyProto::set_allocated_policy_options(::enterprise_management::PolicyOptions* policy_options) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.policy_options_;
  }
  if (policy_options) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(policy_options);
    if (message_arena != submessage_arena) {
      policy_options = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, policy_options, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.policy_options_ = policy_options;
  // @@protoc_insertion_point(field_set_allocated:enterprise_management.BooleanPolicyProto.policy_options)
}

// optional bool value = 2;
inline bool BooleanPolicyProto::_internal_has_value() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool BooleanPolicyProto::has_value() const {
  return _internal_has_value();
}
inline void BooleanPolicyProto::clear_value() {
  _impl_.value_ = false;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline bool BooleanPolicyProto::_internal_value() const {
  return _impl_.value_;
}
inline bool BooleanPolicyProto::value() const {
  // @@protoc_insertion_point(field_get:enterprise_management.BooleanPolicyProto.value)
  return _internal_value();
}
inline void BooleanPolicyProto::_internal_set_value(bool value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.value_ = value;
}
inline void BooleanPolicyProto::set_value(bool value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:enterprise_management.BooleanPolicyProto.value)
}

// -------------------------------------------------------------------

// IntegerPolicyProto

// optional .enterprise_management.PolicyOptions policy_options = 1;
inline bool IntegerPolicyProto::_internal_has_policy_options() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.policy_options_ != nullptr);
  return value;
}
inline bool IntegerPolicyProto::has_policy_options() const {
  return _internal_has_policy_options();
}
inline void IntegerPolicyProto::clear_policy_options() {
  if (_impl_.policy_options_ != nullptr) _impl_.policy_options_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::enterprise_management::PolicyOptions& IntegerPolicyProto::_internal_policy_options() const {
  const ::enterprise_management::PolicyOptions* p = _impl_.policy_options_;
  return p != nullptr ? *p : reinterpret_cast<const ::enterprise_management::PolicyOptions&>(
      ::enterprise_management::_PolicyOptions_default_instance_);
}
inline const ::enterprise_management::PolicyOptions& IntegerPolicyProto::policy_options() const {
  // @@protoc_insertion_point(field_get:enterprise_management.IntegerPolicyProto.policy_options)
  return _internal_policy_options();
}
inline void IntegerPolicyProto::unsafe_arena_set_allocated_policy_options(
    ::enterprise_management::PolicyOptions* policy_options) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.policy_options_);
  }
  _impl_.policy_options_ = policy_options;
  if (policy_options) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:enterprise_management.IntegerPolicyProto.policy_options)
}
inline ::enterprise_management::PolicyOptions* IntegerPolicyProto::release_policy_options() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::enterprise_management::PolicyOptions* temp = _impl_.policy_options_;
  _impl_.policy_options_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::enterprise_management::PolicyOptions* IntegerPolicyProto::unsafe_arena_release_policy_options() {
  // @@protoc_insertion_point(field_release:enterprise_management.IntegerPolicyProto.policy_options)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::enterprise_management::PolicyOptions* temp = _impl_.policy_options_;
  _impl_.policy_options_ = nullptr;
  return temp;
}
inline ::enterprise_management::PolicyOptions* IntegerPolicyProto::_internal_mutable_policy_options() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.policy_options_ == nullptr) {
    auto* p = CreateMaybeMessage<::enterprise_management::PolicyOptions>(GetArenaForAllocation());
    _impl_.policy_options_ = p;
  }
  return _impl_.policy_options_;
}
inline ::enterprise_management::PolicyOptions* IntegerPolicyProto::mutable_policy_options() {
  ::enterprise_management::PolicyOptions* _msg = _internal_mutable_policy_options();
  // @@protoc_insertion_point(field_mutable:enterprise_management.IntegerPolicyProto.policy_options)
  return _msg;
}
inline void IntegerPolicyProto::set_allocated_policy_options(::enterprise_management::PolicyOptions* policy_options) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.policy_options_;
  }
  if (policy_options) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(policy_options);
    if (message_arena != submessage_arena) {
      policy_options = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, policy_options, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.policy_options_ = policy_options;
  // @@protoc_insertion_point(field_set_allocated:enterprise_management.IntegerPolicyProto.policy_options)
}

// optional int64 value = 2;
inline bool IntegerPolicyProto::_internal_has_value() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool IntegerPolicyProto::has_value() const {
  return _internal_has_value();
}
inline void IntegerPolicyProto::clear_value() {
  _impl_.value_ = int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline int64_t IntegerPolicyProto::_internal_value() const {
  return _impl_.value_;
}
inline int64_t IntegerPolicyProto::value() const {
  // @@protoc_insertion_point(field_get:enterprise_management.IntegerPolicyProto.value)
  return _internal_value();
}
inline void IntegerPolicyProto::_internal_set_value(int64_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.value_ = value;
}
inline void IntegerPolicyProto::set_value(int64_t value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:enterprise_management.IntegerPolicyProto.value)
}

// -------------------------------------------------------------------

// StringPolicyProto

// optional .enterprise_management.PolicyOptions policy_options = 1;
inline bool StringPolicyProto::_internal_has_policy_options() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.policy_options_ != nullptr);
  return value;
}
inline bool StringPolicyProto::has_policy_options() const {
  return _internal_has_policy_options();
}
inline void StringPolicyProto::clear_policy_options() {
  if (_impl_.policy_options_ != nullptr) _impl_.policy_options_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::enterprise_management::PolicyOptions& StringPolicyProto::_internal_policy_options() const {
  const ::enterprise_management::PolicyOptions* p = _impl_.policy_options_;
  return p != nullptr ? *p : reinterpret_cast<const ::enterprise_management::PolicyOptions&>(
      ::enterprise_management::_PolicyOptions_default_instance_);
}
inline const ::enterprise_management::PolicyOptions& StringPolicyProto::policy_options() const {
  // @@protoc_insertion_point(field_get:enterprise_management.StringPolicyProto.policy_options)
  return _internal_policy_options();
}
inline void StringPolicyProto::unsafe_arena_set_allocated_policy_options(
    ::enterprise_management::PolicyOptions* policy_options) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.policy_options_);
  }
  _impl_.policy_options_ = policy_options;
  if (policy_options) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:enterprise_management.StringPolicyProto.policy_options)
}
inline ::enterprise_management::PolicyOptions* StringPolicyProto::release_policy_options() {
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::enterprise_management::PolicyOptions* temp = _impl_.policy_options_;
  _impl_.policy_options_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::enterprise_management::PolicyOptions* StringPolicyProto::unsafe_arena_release_policy_options() {
  // @@protoc_insertion_point(field_release:enterprise_management.StringPolicyProto.policy_options)
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::enterprise_management::PolicyOptions* temp = _impl_.policy_options_;
  _impl_.policy_options_ = nullptr;
  return temp;
}
inline ::enterprise_management::PolicyOptions* StringPolicyProto::_internal_mutable_policy_options() {
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.policy_options_ == nullptr) {
    auto* p = CreateMaybeMessage<::enterprise_management::PolicyOptions>(GetArenaForAllocation());
    _impl_.policy_options_ = p;
  }
  return _impl_.policy_options_;
}
inline ::enterprise_management::PolicyOptions* StringPolicyProto::mutable_policy_options() {
  ::enterprise_management::PolicyOptions* _msg = _internal_mutable_policy_options();
  // @@protoc_insertion_point(field_mutable:enterprise_management.StringPolicyProto.policy_options)
  return _msg;
}
inline void StringPolicyProto::set_allocated_policy_options(::enterprise_management::PolicyOptions* policy_options) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.policy_options_;
  }
  if (policy_options) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(policy_options);
    if (message_arena != submessage_arena) {
      policy_options = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, policy_options, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.policy_options_ = policy_options;
  // @@protoc_insertion_point(field_set_allocated:enterprise_management.StringPolicyProto.policy_options)
}

// optional string value = 2;
inline bool StringPolicyProto::_internal_has_value() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool StringPolicyProto::has_value() const {
  return _internal_has_value();
}
inline void StringPolicyProto::clear_value() {
  _impl_.value_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& StringPolicyProto::value() const {
  // @@protoc_insertion_point(field_get:enterprise_management.StringPolicyProto.value)
  return _internal_value();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void StringPolicyProto::set_value(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.value_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:enterprise_management.StringPolicyProto.value)
}
inline std::string* StringPolicyProto::mutable_value() {
  std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:enterprise_management.StringPolicyProto.value)
  return _s;
}
inline const std::string& StringPolicyProto::_internal_value() const {
  return _impl_.value_.Get();
}
inline void StringPolicyProto::_internal_set_value(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.value_.Set(value, GetArenaForAllocation());
}
inline std::string* StringPolicyProto::_internal_mutable_value() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.value_.Mutable(GetArenaForAllocation());
}
inline std::string* StringPolicyProto::release_value() {
  // @@protoc_insertion_point(field_release:enterprise_management.StringPolicyProto.value)
  if (!_internal_has_value()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.value_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.value_.IsDefault()) {
    _impl_.value_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void StringPolicyProto::set_allocated_value(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.value_.SetAllocated(value, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.value_.IsDefault()) {
    _impl_.value_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:enterprise_management.StringPolicyProto.value)
}

// -------------------------------------------------------------------

// StringListPolicyProto

// optional .enterprise_management.PolicyOptions policy_options = 1;
inline bool StringListPolicyProto::_internal_has_policy_options() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.policy_options_ != nullptr);
  return value;
}
inline bool StringListPolicyProto::has_policy_options() const {
  return _internal_has_policy_options();
}
inline void StringListPolicyProto::clear_policy_options() {
  if (_impl_.policy_options_ != nullptr) _impl_.policy_options_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::enterprise_management::PolicyOptions& StringListPolicyProto::_internal_policy_options() const {
  const ::enterprise_management::PolicyOptions* p = _impl_.policy_options_;
  return p != nullptr ? *p : reinterpret_cast<const ::enterprise_management::PolicyOptions&>(
      ::enterprise_management::_PolicyOptions_default_instance_);
}
inline const ::enterprise_management::PolicyOptions& StringListPolicyProto::policy_options() const {
  // @@protoc_insertion_point(field_get:enterprise_management.StringListPolicyProto.policy_options)
  return _internal_policy_options();
}
inline void StringListPolicyProto::unsafe_arena_set_allocated_policy_options(
    ::enterprise_management::PolicyOptions* policy_options) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.policy_options_);
  }
  _impl_.policy_options_ = policy_options;
  if (policy_options) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:enterprise_management.StringListPolicyProto.policy_options)
}
inline ::enterprise_management::PolicyOptions* StringListPolicyProto::release_policy_options() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::enterprise_management::PolicyOptions* temp = _impl_.policy_options_;
  _impl_.policy_options_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::enterprise_management::PolicyOptions* StringListPolicyProto::unsafe_arena_release_policy_options() {
  // @@protoc_insertion_point(field_release:enterprise_management.StringListPolicyProto.policy_options)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::enterprise_management::PolicyOptions* temp = _impl_.policy_options_;
  _impl_.policy_options_ = nullptr;
  return temp;
}
inline ::enterprise_management::PolicyOptions* StringListPolicyProto::_internal_mutable_policy_options() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.policy_options_ == nullptr) {
    auto* p = CreateMaybeMessage<::enterprise_management::PolicyOptions>(GetArenaForAllocation());
    _impl_.policy_options_ = p;
  }
  return _impl_.policy_options_;
}
inline ::enterprise_management::PolicyOptions* StringListPolicyProto::mutable_policy_options() {
  ::enterprise_management::PolicyOptions* _msg = _internal_mutable_policy_options();
  // @@protoc_insertion_point(field_mutable:enterprise_management.StringListPolicyProto.policy_options)
  return _msg;
}
inline void StringListPolicyProto::set_allocated_policy_options(::enterprise_management::PolicyOptions* policy_options) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.policy_options_;
  }
  if (policy_options) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(policy_options);
    if (message_arena != submessage_arena) {
      policy_options = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, policy_options, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.policy_options_ = policy_options;
  // @@protoc_insertion_point(field_set_allocated:enterprise_management.StringListPolicyProto.policy_options)
}

// optional .enterprise_management.StringList value = 2;
inline bool StringListPolicyProto::_internal_has_value() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.value_ != nullptr);
  return value;
}
inline bool StringListPolicyProto::has_value() const {
  return _internal_has_value();
}
inline void StringListPolicyProto::clear_value() {
  if (_impl_.value_ != nullptr) _impl_.value_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::enterprise_management::StringList& StringListPolicyProto::_internal_value() const {
  const ::enterprise_management::StringList* p = _impl_.value_;
  return p != nullptr ? *p : reinterpret_cast<const ::enterprise_management::StringList&>(
      ::enterprise_management::_StringList_default_instance_);
}
inline const ::enterprise_management::StringList& StringListPolicyProto::value() const {
  // @@protoc_insertion_point(field_get:enterprise_management.StringListPolicyProto.value)
  return _internal_value();
}
inline void StringListPolicyProto::unsafe_arena_set_allocated_value(
    ::enterprise_management::StringList* value) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.value_);
  }
  _impl_.value_ = value;
  if (value) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:enterprise_management.StringListPolicyProto.value)
}
inline ::enterprise_management::StringList* StringListPolicyProto::release_value() {
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::enterprise_management::StringList* temp = _impl_.value_;
  _impl_.value_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::enterprise_management::StringList* StringListPolicyProto::unsafe_arena_release_value() {
  // @@protoc_insertion_point(field_release:enterprise_management.StringListPolicyProto.value)
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::enterprise_management::StringList* temp = _impl_.value_;
  _impl_.value_ = nullptr;
  return temp;
}
inline ::enterprise_management::StringList* StringListPolicyProto::_internal_mutable_value() {
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.value_ == nullptr) {
    auto* p = CreateMaybeMessage<::enterprise_management::StringList>(GetArenaForAllocation());
    _impl_.value_ = p;
  }
  return _impl_.value_;
}
inline ::enterprise_management::StringList* StringListPolicyProto::mutable_value() {
  ::enterprise_management::StringList* _msg = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:enterprise_management.StringListPolicyProto.value)
  return _msg;
}
inline void StringListPolicyProto::set_allocated_value(::enterprise_management::StringList* value) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.value_;
  }
  if (value) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(value);
    if (message_arena != submessage_arena) {
      value = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.value_ = value;
  // @@protoc_insertion_point(field_set_allocated:enterprise_management.StringListPolicyProto.value)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace enterprise_management

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::enterprise_management::PolicyOptions_PolicyMode> : ::std::true_type {};

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_policy_5fcommon_5fdefinitions_2eproto
